# Interactive Python Dashboards with Ploty and Dash

Curso: **Udemy**

Instructor:**José Portilla**

Las notas del curso pueden descargarse de https://github.com/Pierian-Data/Plotly-Dashboards-with-Dash

## Preliminares

Aquí puedes encontrar una cheatsheet del lenguaje [Markdown](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)

En esta sección vamos a revisar rápidamente el uso de paquetes básicos de Python: Numpy y Pandas.

Se ejemplificará de manera breve algunas funciones básicas de cada uno.

### Numpy

In [1]:
import numpy as np

In [2]:
mylist = [1, 2, 3, 4]

In [11]:
myarray =n p.array(mylist)

In [4]:
mylist

[1, 2, 3, 4]

In [5]:
type(mylist)

list

In [12]:
type(myarray)

numpy.ndarray

In [13]:
myarray

array([1, 2, 3, 4])

In [14]:
a = np.arange(0,10)

In [15]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
a = np.arange(0, 10, 2)
a

array([0, 2, 4, 6, 8])

In [20]:
np.zeros?

In [21]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [22]:
np.zeros((1,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [23]:
np.zeros((2,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [24]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [25]:
type(1.0)

float

In [26]:
type(1. )

float

In [27]:
type(1)

int

In [29]:
np.random.randint(0,100)

49

In [32]:
np.random.randint(0,100)

80

In [33]:
np.random.randint(0,100,(5,5))

array([[71, 33, 18, 56, 18],
       [81, 11, 29, 37, 14],
       [91,  5, 42, 84, 53],
       [83, 23,  0, 71, 77],
       [45, 76, 12, 51, 83]])

In [34]:
np.linspace?

In [35]:
np.linspace(0, 10, 6)

array([ 0.,  2.,  4.,  6.,  8., 10.])

In [36]:
np.linspace(0, 10, 101)

array([ 0. ,  0.1,  0.2,  0.3,  0.4,  0.5,  0.6,  0.7,  0.8,  0.9,  1. ,
        1.1,  1.2,  1.3,  1.4,  1.5,  1.6,  1.7,  1.8,  1.9,  2. ,  2.1,
        2.2,  2.3,  2.4,  2.5,  2.6,  2.7,  2.8,  2.9,  3. ,  3.1,  3.2,
        3.3,  3.4,  3.5,  3.6,  3.7,  3.8,  3.9,  4. ,  4.1,  4.2,  4.3,
        4.4,  4.5,  4.6,  4.7,  4.8,  4.9,  5. ,  5.1,  5.2,  5.3,  5.4,
        5.5,  5.6,  5.7,  5.8,  5.9,  6. ,  6.1,  6.2,  6.3,  6.4,  6.5,
        6.6,  6.7,  6.8,  6.9,  7. ,  7.1,  7.2,  7.3,  7.4,  7.5,  7.6,
        7.7,  7.8,  7.9,  8. ,  8.1,  8.2,  8.3,  8.4,  8.5,  8.6,  8.7,
        8.8,  8.9,  9. ,  9.1,  9.2,  9.3,  9.4,  9.5,  9.6,  9.7,  9.8,
        9.9, 10. ])

In [37]:
np.linspace(0, 10, 200)

array([ 0.        ,  0.05025126,  0.10050251,  0.15075377,  0.20100503,
        0.25125628,  0.30150754,  0.35175879,  0.40201005,  0.45226131,
        0.50251256,  0.55276382,  0.60301508,  0.65326633,  0.70351759,
        0.75376884,  0.8040201 ,  0.85427136,  0.90452261,  0.95477387,
        1.00502513,  1.05527638,  1.10552764,  1.15577889,  1.20603015,
        1.25628141,  1.30653266,  1.35678392,  1.40703518,  1.45728643,
        1.50753769,  1.55778894,  1.6080402 ,  1.65829146,  1.70854271,
        1.75879397,  1.80904523,  1.85929648,  1.90954774,  1.95979899,
        2.01005025,  2.06030151,  2.11055276,  2.16080402,  2.21105528,
        2.26130653,  2.31155779,  2.36180905,  2.4120603 ,  2.46231156,
        2.51256281,  2.56281407,  2.61306533,  2.66331658,  2.71356784,
        2.7638191 ,  2.81407035,  2.86432161,  2.91457286,  2.96482412,
        3.01507538,  3.06532663,  3.11557789,  3.16582915,  3.2160804 ,
        3.26633166,  3.31658291,  3.36683417,  3.41708543,  3.46

In [38]:
np.random.seed(101)

In [39]:
np.random.randint(0, 100, 10)

array([95, 11, 81, 70, 63, 87, 75,  9, 77, 40])

In [40]:
np.random.randint(0, 100, 10)

array([ 4, 63, 40, 60, 92, 64,  5, 12, 93, 40])

In [48]:
myarray = np.random.randint(0, 100, 10)

In [49]:
myarray

array([24, 36, 63, 19, 35, 30, 10, 60, 20, 27])

In [50]:
myarray.max()

63

In [51]:
myarray.min()

10

In [56]:
myarray.min?

In [57]:
myarray.mean()

32.4

In [58]:
myarray.argmax()

2

In [59]:
myarray.argmin()

6

In [60]:
myarray.reshape((2,5))

array([[24, 36, 63, 19, 35],
       [30, 10, 60, 20, 27]])

Indexing and Masking

In [63]:
mat = np.arange(0,100).reshape(10,10)
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [64]:
mat[5,2]

52

In [65]:
mat[:,2]

array([ 2, 12, 22, 32, 42, 52, 62, 72, 82, 92])

In [66]:
mat[2,:]

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [67]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [68]:
# filtering
mat > 50

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

In [71]:
mat[mat > 50]

array([51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

### Pandas

In [77]:
import pandas as pd
import os

In [109]:
mainpath = "/home/oscar/Documentos/udemy/plotly-dash-joseport/Plotly-Dashboards-with-Dash-master/"
filename = "0-02-Pandas-Crash-Course/salaries.csv"
fullpath = os.path.join(mainpath, filename)

In [110]:
fullpath

'/home/oscar/Documentos/udemy/plotly-dash-joseport/Plotly-Dashboards-with-Dash-master/0-02-Pandas-Crash-Course/salaries.csv'

In [111]:
data = pd.read_csv(fullpath)

In [112]:
data.head()

Name  Salary  Age
0    John   50000   34
1   Sally  120000   45
2  Alyssa   80000   27

In [108]:
mainpath + filename

'/home/oscar/Documentos/udemy/plotly-dash-joseport/Plotly-Dashboards-with-Dash-master/0-02-Pandas-Crash-Course/salaries.csv'

In [106]:
data = pd.read_csv(mainpath + filename)

In [107]:
data.head()

Name  Salary  Age
0    John   50000   34
1   Sally  120000   45
2  Alyssa   80000   27

In [116]:
data_salary = data['Salary']

In [123]:
data_salary

0     50000
1    120000
2     80000
Name: Salary, dtype: int64

In [119]:
type(data_salary)

pandas.core.series.Series

In [120]:
data_name_salary = data[['Name', 'Salary']]

In [121]:
data_name_salary.head()

Name  Salary
0    John   50000
1   Sally  120000
2  Alyssa   80000

In [122]:
type(data_name_salary)

pandas.core.frame.DataFrame

In [124]:
data_salary.min()

50000

In [125]:
data_salary.mean()

83333.33333333333

In [126]:
data_ser_bool = data['Age'] > 30

In [128]:
data_ser_bool

0     True
1     True
2    False
Name: Age, dtype: bool

In [129]:
data_age30 = data[data_ser_bool]

In [130]:
data_age30

Name  Salary  Age
0   John   50000   34
1  Sally  120000   45

In [132]:
# equivalente a 
data[data['Age'] > 30]

Name  Salary  Age
0   John   50000   34
1  Sally  120000   45

In [135]:
data['Age'].unique()

array([34, 45, 27])

In [136]:
data['Age'].nunique()

3

In [137]:
data.columns

Index(['Name', 'Salary', 'Age'], dtype='object')

In [138]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
Name      3 non-null object
Salary    3 non-null int64
Age       3 non-null int64
dtypes: int64(2), object(1)
memory usage: 152.0+ bytes


In [139]:
data.describe()

Salary        Age
count       3.000000   3.000000
mean    83333.333333  35.333333
std     35118.845843   9.073772
min     50000.000000  27.000000
25%     65000.000000  30.500000
50%     80000.000000  34.000000
75%    100000.000000  39.500000
max    120000.000000  45.000000

In [140]:
data.index

RangeIndex(start=0, stop=3, step=1)

### Combinando Numpy-Pandas

In [146]:
mat = np.arange(0,50).reshape(5,10)

In [147]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [148]:
dataframe = pd.DataFrame(data = mat)

In [149]:
dataframe

0   1   2   3   4   5   6   7   8   9
0   0   1   2   3   4   5   6   7   8   9
1  10  11  12  13  14  15  16  17  18  19
2  20  21  22  23  24  25  26  27  28  29
3  30  31  32  33  34  35  36  37  38  39
4  40  41  42  43  44  45  46  47  48  49

In [150]:
mat = np.arange(0,10).reshape(5,2)
dataframe =  pd.DataFrame(data = mat, columns = ['A', 'B'])

In [151]:
dataframe

A  B
0  0  1
1  2  3
2  4  5
3  6  7
4  8  9

### Ejercicios

**Task 0:** Import Numpy and Pandas

In [210]:
import numpy as np
import pandas as pd

**Task 1:** Set Numpy's random number generator seed to 101

In [169]:
np.random.seed(101)

**Task 2:** Create a NumPy Matrix of 100 rows by 5 columns consisting of random integers from 1-100. (Keep in mind that the upper limit may be exclusive.)

In [179]:
mynumbers = np.random.randint(1, 100,(100, 5))

In [180]:
mynumbers

array([[ 1, 13, 18, 76, 80],
       [98, 94, 25, 37, 64],
       [20, 36, 31, 11, 61],
       [21, 28,  9, 87, 27],
       [88, 47, 48, 55, 87],
       [10, 46,  3, 19, 59],
       [93, 12, 11, 95, 36],
       [29,  4, 84, 85, 48],
       [15, 70, 61, 70, 52],
       [ 7, 89, 72, 69, 24],
       [36, 80, 99, 68, 83],
       [58, 78, 47,  4, 47],
       [30, 87, 22, 22, 82],
       [24, 95, 72, 21, 28],
       [76,  6, 50, 87, 90],
       [64, 83, 78,  4, 57],
       [15, 50, 88, 53, 14],
       [48, 50, 25, 21, 65],
       [53, 61, 48, 30, 61],
       [54, 12, 41, 92, 46],
       [98, 25, 37, 39, 10],
       [53, 68, 44,  2, 80],
       [69, 69, 62, 19, 52],
       [15, 29, 18, 88, 47],
       [53, 17, 71, 72, 85],
       [11, 63, 97, 58, 24],
       [87, 86, 27, 77, 67],
       [55, 18, 66, 58, 90],
       [ 3, 81, 51, 67, 89],
       [80, 94,  7, 93, 43],
       [23, 21, 26, 98, 55],
       [72, 73, 81, 94, 65],
       [64, 81, 39, 46, 36],
       [26, 96, 76, 73, 12],
       [77, 80

**Task 3:** Now use pd.DataFrame() to read in this numpy array as a dataframe. Simple pass in the numpy array into that function to get back a dataframe. Pandas will auto label the columns to 0-4.

In [211]:
mydataframe = pd.DataFrame(mynumbers)

In [212]:
mydataframe.head()

0   1   2   3   4
0   1  13  18  76  80
1  98  94  25  37  64
2  20  36  31  11  61
3  21  28   9  87  27
4  88  47  48  55  87

In [183]:
mydataframe.tail()

0   1   2   3   4
95  86  69  99  53  24
96  15  93  26  19  17
97  63  26  80  86  39
98  66  48  51  89  64
99  88  15  64  15  54

**Task 4:** Using your previously created DataFrame, use `[df.columns = [...]]` to rename the pandas columns to be `['f1','f2','f3','f4','label']`.

https://stackoverflow.com/questions/11346283/renaming-columns-in-pandas

In [184]:
mydataframe.columns = ['f1','f2','f3','f4','label']

In [186]:
mydataframe.head()

f1  f2  f3  f4  label
0  55  50  77  99      4
1  33  92  44   8     43
2  67  10   6  27     67
3  23  48  28  47     15
4  53  75  55   4     95

**Task 5:** Alright, all the other tasks were hopefully straightforward. This final task will allow you to quickly check to see if you are at the right level with pandas! Do the following:
* Create a dataframe with the columns `['A','B','C','D']` with each column having 50 rows of random numbers for data. 
* The random numbers should be between 0 and 100.

(Hint: Use numpy to create the numbers, then pass it in to pd.DataFrame(), check out the data= and index= parameters for that call.)

In [214]:
np.random.randint?

In [218]:
mylist = np.random.randint(0, 100,(50,4))
mycolumns = ['A','B','C','D']

In [219]:
df_num = pd.DataFrame(data = mylist, columns = mycolumns)

In [220]:
df_num.head()

A   B   C   D
0  75  77  59  37
1  16  82  64  82
2  51  11  64  44
3  80  83  79  84
4  29  36  83  71

In [221]:
df_num.index

RangeIndex(start=0, stop=50, step=1)